# basic options
title: Mozzlegaming's TSM GitHub
author: Gunnydelight
email: dbartholomew@liberty.edu
description: A wonderful site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
