# basic options
title: Mozzletoff's TSM GitHub
author: Mozzletoff
email: mozzletoffgaming@gmail.com
description: This GitHub page is owned by Mozzletoff. Being created and used as a source of information for www.twitch.tv/mozzletoff. This page will display my TSM3 groups and/or operations into their own TSM.
twitter_username: mozzletoffWOW
youtube_username: mozzletoffWOW
instagram_username: mozzletoffWOW
github_username:  gunnydelight
repository: Gunnydelight/mozzGitHub

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker