# basic options
title: Mozzlegaming's TSM GitHub
author: Mozzletoff
email: mozzletoffgaming@gmail.com
description: This GitHub page is used by www.twitch.tv/mozzletoff in order to provide a website for viewers and the community to copy my current TSM3 groups and/or operations into their own TSM. 
twitter_username: mozzletoffgamin
github_username:  gunnydelight
repository: Gunnydelight/mozzGitHub

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
